In [1]:
#EXPERIMENT 5

In [2]:
#AIM : Creating dimentional arrays

In [5]:
#name : Vedant Saurkar
#Roll no : 55
#Sec : CSE-DS
#Subject : ET-1

In [6]:
import numpy as np

In [7]:
#creating 1D array . (square bracket in round = array)(square bracket=tuple)
a1=np.array([10,20,30,40])

In [8]:
a1

array([10, 20, 30, 40])

In [10]:
#creating 2D array
a2 = np.array([[11,30,20,40],[34,89,47,34]])

In [11]:
a2

array([[11, 30, 20, 40],
       [34, 89, 47, 34]])

In [15]:
#creating 2D array using matrix
a3=np.matrix('11,23;33,45;67,78')
print(a3)

[[11 23]
 [33 45]
 [67 78]]


In [16]:
# Create array of 25 random integers betweeen 20 and 23 (inclusive)
arr = np.random.randint(20, 24, size=25)
print(arr)

[23 22 22 22 23 21 23 21 21 20 20 20 23 22 20 20 23 23 20 20 20 20 23 20
 21]
